routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/scan','SiteController@scan')->name('scan');

// Route::middleware(['checktable'])->group(function () {
Route::get('/','SiteController@index')->name('web_index');
Route::get('/category/{category?}','SiteController@categoryWithItems')->name('category_items');
Route::get('/item/{item}/detail','SiteController@itemDetail')->name('item.detail');

Route::group(['prefix' => 'cart'], function () {
    Route::get('/', 'CartController@cartGet')->name('cart');
    Route::get('/add/{item}', 'CartController@cartAdd')->name('cart.add');
    Route::post('/add/items', 'CartController@cartAddItems')->name('cart.add_items');
    Route::get('/update', 'CartController@cartupdate')->name('cart.update');
    Route::get('/delete/{item_id}', 'CartController@cartDelete')->name('cart.delete');
    Route::post('/store/order', 'CartController@storeOrder')->name('order.store');
});
// });

Route::group(['prefix' => 'admin'], function () {

// Route::Dashboard
Route::group(['prefix' => 'dashboard'], function () {
    
    Route::get('/', 'HomeController@dashboard')->name('dashboard');
    Route::get('/scanner', 'HomeController@scanner')->name('scanner');
    Route::get('/settings', 'HomeController@settings')->name('users.settings');
    Route::patch('/settings', 'HomeController@patch')->name('users.settings');
});

Route::resource('/category','MenuCategoryController');

Route::resource('/items','MenuItemsController');
Route::get('/section/items','MenuItemsController@sectionItems')->name('section_items');

Route::get('/tables/qr/{id}','TablesController@QR');
Route::post('/store/table','TablesController@storeTable')->name('store.table');
Route::resource('/tables','TablesController');

Route::group(['prefix' => 'sections'], function () {

    Route::get('/create', 'MasterSectionController@createSection')->name('section.create');
    Route::post('/store', 'MasterSectionController@storeSection')->name('section.store');

    Route::get('/{p_id}/{type}', 'MasterSectionController@index')->name('master_section');
    Route::get('/{p_id}/{type}/create', 'MasterSectionController@create')->name('master_section.create');
    Route::post('/{p_id}/{type}/store', 'MasterSectionController@store')->name('master_section.store');
    Route::get('/{p_id}/{type}/edit/{master}', 'MasterSectionController@edit')->name('master_section.edit');
    Route::put('/{p_id}/{type}/update/{master}', 'MasterSectionController@update')->name('master_section.update');
});

Route::group(['prefix' => 'order'], function () {
    
    Route::get('/', 'OrderController@order')->name('order');
    Route::get('/datatable', 'OrderController@orderDatatable')->name('order.datatable');
    Route::get('/details/{order_no}', 'OrderController@orderDetails')->name('order_details');
});


Auth::routes();

});
// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Cache Cleared Route
Route::get('exzed/cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
   return 'cache clear';
});



app/Http/Controllers/TablesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Tables;

class TablesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $table = Tables::all();
        return view('tables.index',compact('table'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $isEdit = false;
        return view('tables.create',compact('isEdit'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'table_no'               =>  'required|string|max:255|unique:tables'
        ]);
        Tables:: create([
            'table_no' => $request->table_no
        ]);
        return redirect('/admin/tables');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $table = Tables::find($id);
        $data = [
            'isEdit'            =>  true,
            'table'   =>  $table
        ];
        // return $laboratory_test->includeTest;
        return view('tables.create',$data);
    }

    public function QR($id)
    {
        $curl = curl_init();
        $api='https://chart.apis.google.com/chart?chs=400x400&cht=qr&choe=UTF-8&chl=';
            curl_setopt_array($curl, array(
                CURLOPT_URL => $api,
                CURLOPT_RETURNTRANSFER => true,
                CURLOPT_MAXREDIRS => 10,
                CURLOPT_TIMEOUT => 30,
                CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                CURLOPT_POSTFIELDS => $id,
                CURLOPT_HTTPHEADER => array(
                    'Content-Type: image/png',
                ),
            ));
            $filename=$api.$id;
            $response = curl_exec($curl);
            $err = curl_error($curl);
            curl_close($curl);
            return $filename;
    }   

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'table_no'               =>  'required|string|max:255'
        ]);
        $data = [
            'table_no' => $request->table_no
        ];
        
        Tables::where('id',$id)
        ->update($data);
        
        return redirect('/admin/tables');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function storeTable(Request $request)
    {
        \Cookie::queue('table_id', $request->table_id, 3600);
        $table_id = \Cookie::get('table_id');
        if ( $table_id) {
            $response['success'] = 'This Table ID Added in Session Successfully';
            return response()->json($response, 200);
        } else {
            $response['error'] = 'Oops Something went wrong!';
            return response()->json($response, 409);
        }
    }
}

resources/views/tables/create.blade.php
@extends('layouts.master')

@section('title', 'Add Tables')

@section('top-styles')
 <!-- DataTables -->
 <link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
 <link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
 <link rel="stylesheet" href="{{url('')}}/assets/plugins/select2/css/select2.min.css">
 <style>
   .mt30 {
    margin-top: 35px;
    margin-left: 20px;
}
 </style>
 @endsection

@section('content')
    @section('breadcrumb','Add Tables')
    {{-- {{dd($laboratory_test->laboratory)}} --}}
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- jquery validation -->
              <div class="card">
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <i class="fa fa-users"> </i> Add Tables
                              <button onclick="window.history.back(1)" type="button" class="btn btn-block btn-primary btn-md col-md-2 float-sm-right">Go Back</button>
                        </div>
                        <div class="panel-body">
                          <!-- form start -->
                          <form action="{{$isEdit ? route('tables.update',$table->id) : route('tables.store')}}" role="form" method="POST" id="quickForm" enctype="multipart/form-data">
                            @csrf
                            @if ($isEdit)
                              <input type="hidden" name="_method" value="put">
                            @endif
                            <div class="row">
                              
                              <div class="form-group col-md-4">
                                <label for="fee">Table Number</label>
                                <input type="text" name="table_no" class="form-control"  placeholder="Enter Table Number" value="{{$table->table_no ?? old('table_no')}}">
                                <span class="text-danger">{{$errors->first('table_no') ?? null}}</span>

                              </div>
                            </div>
                              <div class="card-footer">
                                  <button type="submit" class="btn btn-primary">Submit</button>
                              </div>
                          </form>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
              </div>
            <!--/.col (left) -->
            <!-- right column -->
            <div class="col-md-6">
  
            </div>
            <!--/.col (right) -->
          </div>
        
    </div>
  <!-- ./wrapper -->
@section('page-scripts')
<!-- jquery-validation -->
<script src="{{url('')}}/assets/plugins/jquery-validation/jquery.validate.min.js"></script>
<script src="{{url('')}}/assets/plugins/jquery-validation/additional-methods.min.js"></script>
<script src="{{url('')}}/assets/plugins/select2/js/select2.min.js"></script>
@endsection

@endsection

resources/views/tables/index.blade.php
@extends('layouts.master')

@section('title', 'Category ')

@section('top-styles')
<!-- DataTables -->
<link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">

@endsection

@section('content')
@section('breadcrumb','Tables')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <i class="fa fa-users"> </i> Tables
                            <a href="{{route('tables.create')}}" class="col-md-2 float-sm-right">
                                <button type="button" class="btn btn-block btn-primary btn-md">Add Tables</button>
                            </a>
                        </div>
                        <div class="panel-body">
                            <table id="DataTable" class="table table-bordered table-hover table-responsive" width="100%">
                                <thead>
                                    <tr>
                                        <th class="no-sort text-center" width="5%">S.No</th>
                                        <th>Name</th>
                                        <th class="no-sort text-center" width="12%">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $i = 1;
                                    @endphp
                                    @foreach ($table as $c)
                                        <tr>
                                            <td>
                                                {{$i++}}
                                            </td>
                                            <td>
                                                {{$c->table_no}}
                                            </td>
                                            <td>
                                                <a href="{{route('tables.edit',$c->id)}}" class="text-info p-1">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                <button type="button" data-target="#qrModal" data-toggle="modal"  class="btn green qr" id="{{$c->id}}">
                                                    <i class="fa fa-qrcode"></i>
                                                </button>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>



<div id="qrModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">QR Code</h4>
            </div>
            <h1>Your QR is:</h1>
            <img src="" id="image" alt="hibah">
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

<!-- ./wrapper -->
@section('page-scripts')
<!-- DataTables -->
<script src="{{url('')}}/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{url('')}}/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{url('')}}/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{url('')}}/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>

@endsection
@section('custom-script')
<script type="text/javascript">
    $(document).ready(function () {
        var table = $('#DataTable').DataTable();


    });

</script>
<script>
    $(document).on('click','.qr',function(){
        var id=$(this).attr("id");
        $.ajax({
            url:"{{url('')}}/admin/tables/qr/"+id,
            method:"GET",
            error: function (request, error) {
                        alert(" Can't do because: " + error +request);
                    },
            success:function(data){
                console.log(data);
                $('#image').attr("src", data);
            }
        });
    });
</script>
@endsection
@endsection