routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/scan','SiteController@scan')->name('scan');

// Route::middleware(['checktable'])->group(function () {
Route::get('/','SiteController@index')->name('web_index');
Route::get('/category/{category?}','SiteController@categoryWithItems')->name('category_items');
Route::get('/item/{item}/detail','SiteController@itemDetail')->name('item.detail');

Route::group(['prefix' => 'cart'], function () {
    Route::get('/', 'CartController@cartGet')->name('cart');
    Route::get('/add/{item}', 'CartController@cartAdd')->name('cart.add');
    Route::post('/add/items', 'CartController@cartAddItems')->name('cart.add_items');
    Route::get('/update', 'CartController@cartupdate')->name('cart.update');
    Route::get('/delete/{item_id}', 'CartController@cartDelete')->name('cart.delete');
    Route::post('/store/order', 'CartController@storeOrder')->name('order.store');
});
// });

Route::group(['prefix' => 'admin'], function () {

// Route::Dashboard
Route::group(['prefix' => 'dashboard'], function () {
    
    Route::get('/', 'HomeController@dashboard')->name('dashboard');
    Route::get('/scanner', 'HomeController@scanner')->name('scanner');
    Route::get('/settings', 'HomeController@settings')->name('users.settings');
    Route::patch('/settings', 'HomeController@patch')->name('users.settings');
});

Route::resource('/category','MenuCategoryController');

Route::resource('/items','MenuItemsController');
Route::get('/section/items','MenuItemsController@sectionItems')->name('section_items');

Route::get('/tables/qr/{id}','TablesController@QR');
Route::post('/store/table','TablesController@storeTable')->name('store.table');
Route::resource('/tables','TablesController');

Route::group(['prefix' => 'sections'], function () {

    Route::get('/create', 'MasterSectionController@createSection')->name('section.create');
    Route::post('/store', 'MasterSectionController@storeSection')->name('section.store');

    Route::get('/{p_id}/{type}', 'MasterSectionController@index')->name('master_section');
    Route::get('/{p_id}/{type}/create', 'MasterSectionController@create')->name('master_section.create');
    Route::post('/{p_id}/{type}/store', 'MasterSectionController@store')->name('master_section.store');
    Route::get('/{p_id}/{type}/edit/{master}', 'MasterSectionController@edit')->name('master_section.edit');
    Route::put('/{p_id}/{type}/update/{master}', 'MasterSectionController@update')->name('master_section.update');
});

Route::group(['prefix' => 'order'], function () {
    
    Route::get('/', 'OrderController@order')->name('order');
    Route::get('/datatable', 'OrderController@orderDatatable')->name('order.datatable');
    Route::get('/details/{order_no}', 'OrderController@orderDetails')->name('order_details');
});


Auth::routes();

});
// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// Cache Cleared Route
Route::get('exzed/cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('view:clear');
    Artisan::call('route:clear');
    Artisan::call('config:clear');
   return 'cache clear';
});



app/Items.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\ItemDetail;

class Items extends Model
{
    protected $table = 'menu_items';
    protected $fillable = [
        'name',
        'image',
        'description',
        'price',
        'c_id',
        'status',
    ];

    /**
     * Get all of the sections for the Items
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function sections()
    {
        return $this->hasMany(ItemDetail::class, 'item_id', 'id');
    }
    public function category()
    {
        return $this->hasOne('App\Category','id','c_id');
    }
}

resources/views/items/create.blade.php
@extends('layouts.master')

@section('title', 'Add Menu Item')

@section('top-styles')
 <!-- DataTables -->
 <link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
 <link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
 <link rel="stylesheet" href="{{url('')}}/assets/plugins/select2/css/select2.min.css">
 <style>
   .mt30 {
    margin-top: 35px;
    margin-left: 20px;
  }
  li.select2-selection__choice {
      color: #6d6a6a !important;
  }
  span.fa.fa-close {
        float: right;
        color: #f05050d6;
        font-size: 20px;
        position: relative;
        bottom: 0px;
        left: 0px;
    }
    i.fa.fa-minus {
        /* float: right; */
        position: relative;
        padding: 8px;
        background: #ff5722;
        color: white;
        cursor: pointer;
    }
    .fa-plus {
    position: relative;
    padding: 8px;
    background: #8BC34A;
    color: white;
    cursor: pointer;
    }
    i#add-court {
        left: 135px;
    }
    i.fa.fa-minus.remove-court {
        left: 140px;
    }


 </style>
 @endsection

@section('content')
    @section('breadcrumb','Add Menu Item')
    {{-- {{dd($laboratory_test->laboratory)}} --}}
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- jquery validation -->
              <div class="card">
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <i class="fa fa-users"> </i> Add Menu Item
                              <button onclick="window.history.back(1)" type="button" class="btn btn-block btn-primary btn-md col-md-2 float-sm-right">Go Back</button>
                        </div>
                        <div class="panel-body">
                          <!-- form start -->
                          <form action="{{$isEdit ? route('items.update',$item->id) : route('items.store')}}" role="form" method="POST" id="quickForm" enctype="multipart/form-data">
                            @csrf
                            @if ($isEdit)
                              <input type="hidden" name="_method" value="put">
                            @endif
                            <div class="row">
                              <div class="col-md-4">
                                  <div class="avatar-upload" style="height: 200px;">
                                      <div class="avatar-edit">
                                          <input type='file' name="image" id="imageUpload1"
                                              accept=".png, .jpg, .jpeg" />
                                          <label for="imageUpload1"><span>{{ __('Featured image')}} </span></label>
                                      </div>
                                      <div class="avatar-preview">
                                          <div id="imagePreview1"
                                              style="background-image : url({{$isEdit ? url('').'/uploads/'.$item->image : url('').'/uploads/placeholder.jpg'}}">
                                          </div>
                                      </div>
                                  </div>
                                  <span class="text-danger">{{$errors->first('image') ?? null}}</span>
                              </div>
                              <div class="col-md-8">
                                <div class="form-group" style="margin-bottom: 35px">
                                  <label for="name">Select Category</label>
                                  <select name="c_id" class="form-control"> 
                                    <option value="" selected disabled>Select Category</option>
                                    @foreach ($cat as $c)
                                        <option value="{{$c->id}}" 
                                        @if ($isEdit)
                                            {{$item->c_id == $c->id ? 'selected' : null}}
                                        @endif>{{$c->name}} </option>
                                    @endforeach
                                  </select>
                                  <span class="text-danger">{{$errors->first('c_id') ?? null}}</span>
                                </div>
                                <div class="form-group">
                                  <label for="fee">Item Name</label>
                                  <input type="text" name="name" class="form-control"  placeholder="Enter Item Name" value="{{$item->name ?? old('name')}}">
                                  <span class="text-danger">{{$errors->first('name') ?? null}}</span>

                                </div>
                                
                              </div>
                            </div>
                            <br>
                              <div class="row">
                              <div class="form-group col-md-12">
                                <label for="fee">Price</label>
                                <input type="text" name="price" class="form-control"  placeholder="Enter Item Price" value="{{$item->price ?? old('price')}}">
                                <span class="text-danger">{{$errors->first('price') ?? null}}</span>

                              </div>
                              <div class="form-group col-md-12">
                                <label for="fee">Description</label>
                                <input type="text" name="description" class="form-control"  placeholder="Enter Item Description" value="{{$item->description ?? old('description')}}">
                                <span class="text-danger">{{$errors->first('description') ?? null}}</span>

                              </div>
                              <div class="form-group col-md-12">
                                <h3 style="font-weight: bold;margin-bottom:0px" for="add_detail">Add Detail </h3> <span class="text-danger">Note: If you dont want to add details then leave section empty</span>
                                <br>
                                <br>
                                <i class="fa fa-plus" id="add"></i>
                                <i class="fa fa-minus remove"></i>
                              </div>
                              <div id="prize-section" class="col-md-12">
                                @if ($isEdit)
                                @php
                                    $i=1;
                                @endphp
                                @foreach ($item->sections as $key => $section)
                                {{-- {{dd($section->singleItem)}} --}}
                                  <div class="row prize col-md-12">
                                    <div class="form-group col-md-6">
                                      <label for="name">Select Section</label>
                                      <select name="section_id[]" id="1" class="form-control section_id"> 
                                        <option value="{{$section->singleItem->id}}">{{$section->singleItem->name}}
                                       </option>

                                      </select>
                                      <span class="text-danger">{{$errors->first('section_id') ?? null}}</span>
                                    </div>
                                    <div class="form-group col-md-6">
                                      <label for="name">Select Items</label>
                                      <select name="is_paid[]" id="is_paid" class="form-control">
                                            <option value="1" {{$section->is_paid == 1 ? 'selected' : null}}>Paid</option>
                                            <option value="0" {{$section->is_paid == 0 ? 'selected' : null}}>Free</option>
                                      </select>
                                      <span class="text-danger">{{$errors->first('is_paid') ?? null}}</span>
                                    </div>
                                  </div>
                                @endforeach
                                @else
                                  <div class="row prize col-md-12">
                                    <div class="form-group col-md-6">
                                      <label for="name">Select Section</label>
                                      <select name="section_id[]" id="1" class="form-control section_id"> 
                                        <option value="" selected disabled>Select Section</option>

                                        @foreach ($sections as $key=> $section)
                                            <option value="{{$section->id}}">{{$section->name}} </option>
                                        @endforeach
                                      </select>
                                      <span class="text-danger">{{$errors->first('section_id') ?? null}}</span>
                                    </div>
                                    <div class="form-group col-md-6">
                                      <label for="name">Amount</label>
                                      <select name="is_paid[]" id="is_paid" class="form-control">
                                            <option value="1">Paid</option>
                                            <option value="0">Free</option>
                                      </select>
                                      <span class="text-danger">{{$errors->first('is_paid') ?? null}}</span>
                                    </div>
                                  </div>
                                    
                                @endif
                              </div>
                            </div>
                            </div>
                              <div class="card-footer">
                                  <button type="submit" class="btn btn-primary">Submit</button>
                              </div>
                          </form>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
              </div>
              <!-- /.card -->
              </div>
            <!--/.col (left) -->
            <!-- right column -->
            <div class="col-md-6">
  
            </div>
            <!--/.col (right) -->
          </div>
        
    </div>
  <!-- ./wrapper -->
@section('page-scripts')
<!-- jquery-validation -->
<script src="{{url('')}}/assets/plugins/jquery-validation/jquery.validate.min.js"></script>
<script src="{{url('')}}/assets/plugins/jquery-validation/additional-methods.min.js"></script>
<script src="{{url('')}}/assets/plugins/select2/js/select2.min.js"></script>

@endsection
@section('custom-script')
<script type="text/javascript">
    $(document).ready(function () {
    
      $('.select').select2();

      $('#quickForm').validate({
        rules: {
          name: { required: true, },
          description: { required: true, },
        },
        errorElement: 'span',
        errorPlacement: function (error, element) {
          error.addClass('invalid-feedback');
          element.closest('.form-group').append(error);
        },
        highlight: function (element, errorClass, validClass) {
          $(element).addClass('is-invalid');
        },
        unhighlight: function (element, errorClass, validClass) {
          $(element).removeClass('is-invalid');
        }
      });

      function readURL(input, number) {
          if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $('#imagePreview' + number).css('background-image', 'url(' + e.target.result + ')');
                $('#imagePreview' + number).hide();
                $('#imagePreview' + number).fadeIn(650);
            }
            reader.readAsDataURL(input.files[0]);
          }
        }
        $("#imageUpload1").change(function () {
            readURL(this, 1);
        });

    $('#add').click(function(){
      var id = $('.section_id').last().attr('id');
      id  = id+1; 
      $('#prize-section').append(`
        <div class="row prize col-md-12">
          <div class="form-group col-md-6">
            <label for="name">Select Section</label>
            <select name="section_id[]" id="1" class="form-control section_id"> 
              <option value="" selected disabled>Select Section</option>

              @foreach ($sections as $key=> $section)
                  <option value="{{$section->id}}">{{$section->name}} </option>
              @endforeach
            </select>
            <span class="text-danger">{{$errors->first('section_id') ?? null}}</span>
          </div>
          <div class="form-group col-md-6">
            <label for="name">Amount</label>
            <select name="is_paid[]" id="is_paid" class="form-control">
                  <option value="1">Paid</option>
                  <option value="0">Free</option>
            </select>
            <span class="text-danger">{{$errors->first('is_paid') ?? null}}</span>
          </div>
        </div>
        `);
    });
    $('.remove').click(function(){
      $('#prize-section .prize:last-child').remove();
    });
  });
</script>
@endsection
@endsection

resources/views/items/index.blade.php
@extends('layouts.master')

@section('title', 'Items ')

@section('top-styles')
<!-- DataTables -->
<link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="{{url('')}}/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">

@endsection

@section('content')
@section('breadcrumb','Tables')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="panel panel-primary">
                        @if (session('message'))
                            <p class="alert alert-success"> {{session('message')}}</p>
                        @endif
                        <div class="panel-heading">
                            <i class="fa fa-users"> </i> Menu Items
                            <a href="{{route('items.create')}}" class="col-md-2 float-sm-right">
                                <button type="button" class="btn btn-block btn-primary btn-md">Add Menu Item</button>
                            </a>
                        </div>
                        <div class="panel-body">
                            <table id="DataTable" class="table table-bordered table-hover table-responsive" width="100%">
                                <thead>
                                    <tr>
                                        <th class="no-sort text-center" width="5%">S.No</th>
                                        <th>Image</th>
                                        <th>Name</th>
                                        <th>Category</th>
                                        <th>Price</th>
                                        <th>Description</th>
                                        <th class="no-sort text-center" width="12%">Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $i = 1;
                                    @endphp
                                    @foreach ($items as $c)
                                        <tr>
                                            <td>
                                                {{$i++}}
                                            </td>
                                            <td>
                                                <img src="{{url('').'/uploads/'.$c->image}}" height="50px">
                                            </td>
                                            <td>
                                                {{$c->name}}
                                            </td>
                                            <td>
                                                {{$c->category->name}}
                                            </td>
                                            <td>
                                                {{$c->price}}
                                            </td>
                                            <td>
                                                {{$c->description == null ? '-' : $c->description}}
                                            </td>
                                            <td>
                                                <a href="{{route('items.edit',$c->id)}}" class="text-info p-1">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>
<!-- ./wrapper -->
@section('page-scripts')
<!-- DataTables -->
<script src="{{url('')}}/assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{url('')}}/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="{{url('')}}/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="{{url('')}}/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>

@endsection
@section('custom-script')
<script type="text/javascript">
    $(document).ready(function () {
        var table = $('#DataTable').DataTable();
    });

</script>
@endsection
@endsection